setTimeout(function(){
  var btn=document.getElementById('pdfBtn');
  if(!btn) return;
  btn.textContent='Abrir PDF premium';
  btn.onclick=function(){
    var db=(document.getElementById('reportName')||{}).value||'Rotagyn';
    var kpis=[].slice.call(document.querySelectorAll('.kpi')).map(function(k){return{t:(k.querySelector('span')||{}).textContent||'',v:(k.querySelector('b')||{}).textContent||'',s:(k.querySelector('small')||{}).textContent||''}});
    var problems=[].slice.call(document.querySelectorAll('#problems .barrow')).map(function(r){var c=r.children;return{l:c[0].textContent,v:c[2].textContent}});
    var rows=[].slice.call(document.querySelectorAll('#table tbody tr')).slice(0,18).map(function(tr){return [].slice.call(tr.children).map(function(td){return td.textContent.trim()})});
    if(!rows.length){alert('Carregue a análise antes de gerar o relatório.');return;}
    var avg=(kpis[0]||{}).v||'0';
    var exec=Number(avg)>=80?'A frota apresenta um cenário saudável, com baixa incidência de falhas críticas e boa estabilidade operacional.':Number(avg)>=60?'A frota está em atenção. Existem indícios claros de degradação operacional que exigem ação preventiva.':'A frota está em estado crítico. É necessário atuar imediatamente nos veículos com maior risco operacional.';
    var html='<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Fleet Health Report</title><link rel="stylesheet" href="premium.css?v=0.3.0"><style>body{background:#fff!important;padding:0!important}.pdf-stage{position:static!important;left:auto!important;z-index:auto!important}.pdf-page{page-break-after:always}.pdf-page.landscape{page:landscape}@page{size:A4;margin:0}@page landscape{size:A4 landscape;margin:0}</style></head><body><div class="pdf-stage">'+
    '<div class="pdf-page"><div class="pdf-topbar"></div><div class="pdf-brand"><img class="pdf-logo" src="../assets/rotagyn-logo.svg"><div class="pdf-chip">RELATÓRIO INTERNO</div></div><div class="pdf-cover"><h2>Fleet Health Score</h2><p>Relatório premium de saúde técnica da frota</p><div class="pdf-meta"><div class="pdf-chip">Banco/Base: '+db+'</div><div class="pdf-chip">Base ativa: 30 dias</div><div class="pdf-chip">Score: últimos 7 dias</div><div class="pdf-chip">Gerado em '+new Date().toLocaleString('pt-BR')+'</div></div><div class="pdf-cover-grid"><div class="pdf-highlight"><div style="font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#bae6fd;font-weight:900">Resumo executivo</div><div style="font-size:24px;font-weight:900;margin-top:10px;line-height:1.22">'+exec+'</div><div style="margin-top:18px;color:#dbeafe;font-size:13px;line-height:1.6">Priorizar veículos com <b>score abaixo de 60</b>, casos sem dados há mais de <b>7 dias</b>, eventos de <b>desconexão</b> e ocorrências de <b>tensão fora do padrão</b>.</div></div><div class="pdf-highlight" style="display:flex;align-items:center;justify-content:center"><div class="pdf-index"><b>'+avg+'</b><span>Health Index</span></div></div></div></div><div class="pdf-footer"><span>Fleet Health Score • Rotagyn</span><span>Página 1</span></div></div>'+
    '<div class="pdf-page"><div class="pdf-topbar"></div><div class="pdf-brand"><div><h1 class="pdf-title">Resumo executivo</h1><div class="pdf-subtitle">KPIs e leitura estratégica da frota</div></div><img class="pdf-logo" src="../assets/rotagyn-logo.svg"></div><div class="pdf-grid-4">'+kpis.slice(0,4).map(function(k,i){return'<div class="pdf-kpi"><small>'+k.t+'</small><b style="color:'+(i>1?'#ef4444':'#0ea5e9')+'">'+k.v+'</b><span>'+k.s+'</span></div>'}).join('')+'</div><div class="pdf-section"><div class="pdf-two-col"><div class="pdf-card"><div class="pdf-section-title">Top problemas</div><div class="pdf-bars">'+problems.map(function(p){return'<div class="row"><div>'+p.l+'</div><div class="track"><div class="fill" style="width:70%;background:#0ea5e9"></div></div><div>'+p.v+'</div></div>'}).join('')+'</div></div><div class="pdf-card"><div class="pdf-section-title">Leitura executiva</div><div class="pdf-summary-box"><b>Banco/Base:</b> '+db+'</div><div class="pdf-summary-box"><b>Condição atual:</b> '+exec+'</div><div class="pdf-summary-box"><b>Prioridade:</b> atuar primeiro em score abaixo de 60, sem dados 7d+, tensão fora e eventos de desconexão.</div></div></div></div><div class="pdf-footer"><span>Fleet Health Score • Resumo Executivo</span><span>Página 2</span></div></div>'+
    '<div class="pdf-page landscape"><div class="pdf-topbar"></div><div class="pdf-brand"><div><h1 class="pdf-title">Ranking técnico da frota</h1><div class="pdf-subtitle">Veículos mais críticos e suas causas principais</div></div><img class="pdf-logo" src="../assets/rotagyn-logo.svg"></div><table class="pdf-table"><thead><tr><th class="c-num">#</th><th class="c-score">Score</th><th class="c-plate">Placa</th><th>Veículo</th><th class="c-last">Último</th><th>Problema</th><th class="c-status">Status</th></tr></thead><tbody>'+rows.map(function(r){return'<tr><td>'+r[0]+'</td><td style="font-weight:900;color:#ef4444">'+r[1]+'</td><td style="font-weight:800">'+r[2]+'</td><td>'+r[3]+'</td><td>'+r[4]+'</td><td>'+r[5]+'</td><td><span class="pdf-badge pdf-critical">'+r[6]+'</span></td></tr>'}).join('')+'</tbody></table><div class="pdf-footer" style="left:36px;right:36px"><span>Fleet Health Score • Ranking Técnico</span><span>Página 3</span></div></div>'+
    '<div class="pdf-page"><div class="pdf-topbar"></div><div class="pdf-brand"><div><h1 class="pdf-title">Plano de ação recomendado</h1><div class="pdf-subtitle">Prioridades de atuação operacional</div></div><img class="pdf-logo" src="../assets/rotagyn-logo.svg"></div><div class="pdf-action"><h4>Prioridade 1 — veículos sem dados há mais de 7 dias</h4><p>Validar energia, dados móveis, GPS, comunicação e integridade do equipamento.</p></div><div class="pdf-action"><h4>Prioridade 2 — tensão baixa ou alta recorrente</h4><p>Revisar bateria, alternador, aterramento, alimentação do dispositivo e qualidade da instalação elétrica.</p></div><div class="pdf-action"><h4>Prioridade 3 — desconexão e possível remoção não autorizada</h4><p>Tratar de forma imediata os casos de unplugged/desconectado.</p></div><div class="pdf-action"><h4>Prioridade 4 — reboots e falhas GPS reincidentes</h4><p>Abrir análise técnica focando em firmware, posição do equipamento e estabilidade da alimentação.</p></div><div class="pdf-footer"><span>Fleet Health Score • Plano de Ação</span><span>Página 4</span></div></div></div><script>setTimeout(function(){window.print()},600)<\/script></body></html>';
    var w=window.open('','_blank');
    if(!w){alert('Permita pop-ups para abrir o PDF premium.');return;}
    w.document.open();w.document.write(html);w.document.close();
  };
},900);
