(function(){
'use strict';
const DAY=86400000,LOGO='../assets/rotagyn-logo.svg';
let apiRef=null,stateRef={},vehicles=[],filtered=[],dbName='Rotagyn';
const $=id=>document.getElementById(id);
const pct=(a,b)=>b?Math.round((a/b)*100):0;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const clean=s=>String(s||'Rotagyn').replace(/[\\/:*?"<>|]+/g,'-').trim()||'Rotagyn';
const apiGet=(api,type,search)=>new Promise((ok,err)=>api.call('Get',{typeName:type,search:search||{}},ok,err));
function scVar(s){return s>=80?'var(--green)':s>=60?'var(--yellow)':s>=40?'var(--orange)':'var(--red)'}
function scLabel(s){return s>=80?'Saudável':s>=60?'Atenção':s>=40?'Crítico':'Risco alto'}
function scClass(s){return s>=80?'okb':s>=60?'warnb':s>=40?'orangeb':'riskb'}
function has(t,arr){t=String(t||'').toLowerCase();return arr.some(x=>t.includes(x.toLowerCase()))}
function dname(r){return String(r&&r.diagnostic&&(r.diagnostic.id||r.diagnostic.name)||'')}
function eventDate(r){return r.dateTime||r.activeFrom||r.fromDate||r.startTime||r.addDate||null}
function fmtDate(d){try{return new Date(d).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}catch(e){return String(d||'')}}
function uniqDates(list){const seen={};return list.filter(Boolean).sort((a,b)=>new Date(b)-new Date(a)).filter(d=>{const k=new Date(d).toISOString();if(seen[k])return false;seen[k]=true;return true})}
function unplug(r){const n=dname(r).toLowerCase();return n.includes('diagnosticdevicehasbeenunpluggedid')||n.includes('devicehasbeenunplugged')||n.includes('unplugged')||n.includes('desconectado')||n.includes('removido')||n.includes('remoção')||n.includes('remocao')}
function problem(v){if(v.unplugged>0)return'Possível remoção não autorizada';if(v.dias>=7)return'Sem dados '+v.dias+' dias';if(v.vlow>0)return'Tensão baixa';if(v.vhigh>0)return'Tensão alta';if(v.reboots>2)return'Reboot excessivo';if(v.gps>0)return'Falha GPS';if(v.faults>0)return'Falha device';return'Sem alerta crítico'}
function executive(avg){if(avg>=80)return'A frota apresenta um cenário saudável, com baixa incidência de falhas críticas e boa estabilidade operacional.';if(avg>=60)return'A frota está em atenção. Existem indícios claros de degradação operacional que exigem ação preventiva.';return'A frota está em estado crítico. É necessário atuar imediatamente nos veículos com maior risco operacional.'}
function analyze(records,v){
 const a={reboots:0,gps:0,vlow:0,vhigh:0,faults:0,unplugged:0,minV:null,maxV:null,voltageTotal:0,removalDates:[]};
 records.forEach(r=>{const n=dname(r),val=Number(r.data);if(unplug(r)){a.unplugged++;const d=eventDate(r);if(d)a.removalDates.push(d)}if(has(n,['reboot','restart']))a.reboots++;if(has(n,['gps invalid','gps failure','no gps','gps']))a.gps++;if(has(n,['device fault','internal device','malfunction']))a.faults++;if(has(n,['external voltage','device voltage','battery voltage','voltage'])&&!isNaN(val)){a.voltageTotal++;a.minV=a.minV==null?val:Math.min(a.minV,val);a.maxV=a.maxV==null?val:Math.max(a.maxV,val);if(val<20){if(val<11)a.vlow++;if(val>14.8)a.vhigh++}else{if(val<22)a.vlow++;if(val>29)a.vhigh++}}});
 let p=0,ds=v.lastDate?Math.floor((Date.now()-new Date(v.lastDate).getTime())/DAY):999;
 p+=ds<1?30:ds<2?22:ds<4?12:ds<7?5:0;
 p+=a.reboots===0?20:a.reboots<=2?15:a.reboots<=5?10:a.reboots<=10?5:0;
 p+=a.gps===0?15:a.gps<=3?11:a.gps<=10?7:0;
 const vb=a.vlow+a.vhigh;p+=vb===0?20:vb<=5?15:vb<=20?9:0;
 p+=a.faults===0?15:a.faults<=2?10:a.faults<=6?5:0;
 if(a.unplugged>0)p=Math.min(p,25); if(ds>=7)p=Math.min(p,45);
 a.score=Math.max(0,Math.round(p));a.dias=ds;
 a.removalDates=uniqDates(a.removalDates);
 a.removalDatesText=a.removalDates.length?a.removalDates.slice(0,3).map(fmtDate).join(' | '):'-';
 a.lastRemovalDate=a.removalDates.length?fmtDate(a.removalDates[0]):'-';
 return a;
}
function summary(list){const total=list.length||1,avg=Math.round(list.reduce((s,v)=>s+v.score,0)/total);return{total:list.length,avg,healthy:list.filter(v=>v.score>=80).length,attention:list.filter(v=>v.score>=60&&v.score<80).length,critical:list.filter(v=>v.score<60&&v.score>=40).length,risk:list.filter(v=>v.score<40).length,nodata:list.filter(v=>v.dias>=7).length,unplugged:list.filter(v=>v.unplugged>0).length,voltage:list.filter(v=>v.vlow+v.vhigh>0).length,gps:list.filter(v=>v.gps>0).length,reboot:list.filter(v=>v.reboots>2).length}}
function topProblems(list){const s=summary(list);return[{label:'Sem dados 7d+',value:s.nodata,color:'#ef4444'},{label:'Tensão fora',value:s.voltage,color:'#f97316'},{label:'Falha GPS',value:s.gps,color:'#f59e0b'},{label:'Reboot excessivo',value:s.reboot,color:'#0ea5e9'},{label:'Possível remoção',value:s.unplugged,color:'#dc2626'}]}
function getDb(api,state){return(state&&(state.database||state.databaseName))||(api&&api.credentials&&api.credentials.database)||localStorage.getItem('fleetReportName')||'Rotagyn'}
function status(t){const e=$('statusBox');if(e)e.textContent=t}
function alertMsg(t,cls){const e=$('alertBox');if(!e)return;e.className='alert '+(cls||'');e.innerHTML=t||''}
function shell(){
 $('app').innerHTML=`<div class="head"><div class="brand"><img class="logo" src="${LOGO}"><div><div class="title">Fleet Health Reports</div><div class="sub">RELATÓRIO PDF PREMIUM • GEOTAB ADD-IN</div></div></div><div class="pill" id="statusBox">Conectando...</div></div><div class="bar"><button class="primary" id="loadBtn">Gerar análise</button><button class="soft" id="pdfBtn">Gerar PDF imagem premium</button><button id="csvBtn">Exportar CSV</button><button id="demoBtn">Dados simulados</button><input id="reportName" placeholder="Nome do banco/base" value="${esc(dbName)}"><select id="scoreFilter"><option value="">Todos os veículos</option><option value="critical">Críticos + risco alto</option><option value="nodata">Sem dados 7d+</option><option value="voltage">Tensão fora</option><option value="removal">Possível remoção</option></select></div><div class="info"><span>Base ativa: <b>30 dias</b></span><span>Score: <b>7 dias</b></span><span>Banco/Base: <b id="dbBox">${esc(dbName)}</b></span><span>Veículos no relatório: <b id="countBox">0</b></span></div><div id="alertBox" class="alert">Use dentro do MyGeotab para carregar dados reais. O relatório agora mostra as datas das possíveis remoções.</div><div id="kpis" class="grid"></div><div class="cols"><div class="panel"><div class="pt">Top problemas</div><div id="problems"></div></div><div class="panel"><div class="pt">Leitura executiva</div><div id="exec" class="exec"></div></div></div><div class="panel"><div class="pt">Ranking técnico da frota</div><div id="table" class="tablewrap"></div></div>`;
 $('loadBtn').onclick=()=>load(apiRef);$('csvBtn').onclick=exportCSV;$('demoBtn').onclick=demo;$('scoreFilter').onchange=apply;$('reportName').oninput=()=>{dbName=$('reportName').value||'Rotagyn';localStorage.setItem('fleetReportName',dbName);render()};
}
async function load(api){
 if(!api){alertMsg('Abra esta tela dentro do MyGeotab para carregar dados reais. Use Dados simulados para validar o PDF.','err');return}
 apiRef=api;dbName=getDb(api,stateRef);$('reportName').value=dbName;localStorage.setItem('fleetReportName',dbName);status('Carregando...');alertMsg('Consultando Device, DeviceStatusInfo, StatusData e FaultData...');
 const from30=new Date(Date.now()-30*DAY),from7=new Date(Date.now()-7*DAY);
 try{const devs=await apiGet(api,'Device',{isArchived:false}),dm={};devs.forEach(d=>{if(!d.name||d.isActive===false)return;if(d.toDate&&new Date(d.toDate)<new Date())return;dm[d.id]={nome:d.name,placa:d.licensePlate||d.name,grupos:(d.groups||[]).map(g=>g.id)}});const dsi=await apiGet(api,'DeviceStatusInfo',{}),active={};dsi.forEach(s=>{const id=s.device&&s.device.id;if(!id||!dm[id]||!s.dateTime||new Date(s.dateTime)<from30||s.latitude==null||s.longitude==null)return;if(!active[id]||new Date(s.dateTime)>new Date(active[id].dateTime))active[id]=s});let st=[],faults=[];try{st=await apiGet(api,'StatusData',{fromDate:from7.toISOString(),toDate:new Date().toISOString()})}catch(e){}try{faults=await apiGet(api,'FaultData',{fromDate:from30.toISOString(),toDate:new Date().toISOString()})}catch(e){}const by={};st.concat(faults).forEach(r=>{const id=r.device&&r.device.id;if(id)(by[id]||(by[id]=[])).push(r)});vehicles=Object.keys(active).map(id=>{const s=active[id],i=dm[id],base={id,nome:i.nome,placa:i.placa,grupos:i.grupos,lastDate:s.dateTime,online:!!s.isDeviceCommunicating};return Object.assign(base,analyze(by[id]||[],base))}).sort((a,b)=>a.score-b.score);filtered=[...vehicles];status(vehicles.length+' veículos');alertMsg('Análise concluída. Possíveis remoções com datas foram carregadas.','ok');render()}catch(e){console.error(e);status('Erro');alertMsg('Erro ao carregar dados: '+(e.message||e),'err')}
}
function apply(){const f=$('scoreFilter').value;filtered=vehicles.filter(v=>f==='critical'?v.score<60:f==='nodata'?v.dias>=7:f==='voltage'?(v.vlow+v.vhigh)>0:f==='removal'?v.unplugged>0:true);render()}
function render(){if(!$('kpis'))return;dbName=$('reportName')&&$('reportName').value?$('reportName').value:'Rotagyn';const s=summary(filtered);$('dbBox').textContent=dbName;$('countBox').textContent=s.total.toLocaleString('pt-BR');$('kpis').innerHTML=[['Fleet Health Index',s.avg,'de 100','var(--blue)'],['Veículos analisados',s.total,'base filtrada','var(--txt)'],['Críticos',s.critical+s.risk,pct(s.critical+s.risk,s.total)+'% da frota','var(--red)'],['Possível remoção',s.unplugged,'com data do evento','var(--red)'],['Sem dados 7d+',s.nodata,'prioridade operacional','var(--orange)']].map(c=>`<div class="kpi"><span>${c[0]}</span><b style="color:${c[3]}">${c[1]}</b><small>${c[2]}</small></div>`).join('');const probs=topProblems(filtered),max=Math.max(1,...probs.map(p=>p.value));$('problems').innerHTML=probs.map(p=>`<div class="barrow"><b>${p.label}</b><div class="track"><div class="fill" style="width:${Math.round(p.value/max*100)}%;background:${p.color}"></div></div><span>${p.value}</span></div>`).join('');$('exec').innerHTML=`<div><b>Banco/Base:</b> ${esc(dbName)}</div><div><b>Leitura:</b> ${executive(s.avg)}</div><div><b>Possíveis remoções:</b> ${s.unplugged} veículo(s) com evento identificado. A data aparece no ranking e no CSV.</div>`;$('table').innerHTML='<table><thead><tr><th>#</th><th>Score</th><th>Placa</th><th>Veículo</th><th>Último dado</th><th>Problema principal</th><th>Datas possível remoção</th><th>Status</th></tr></thead><tbody>'+filtered.slice(0,80).map((v,i)=>`<tr><td>${i+1}</td><td><b style="color:${scVar(v.score)}">${v.score}</b></td><td><b style="font-family:var(--mono);color:var(--txt)">${esc(v.placa||'-')}</b></td><td class="vehicleCell" title="${esc(v.nome)}">${esc(v.nome)}</td><td>${v.dias>=7?'7d+':v.dias+'d'}</td><td>${esc(problem(v))}</td><td>${esc(v.removalDatesText||'-')}</td><td><span class="badge ${scClass(v.score)}">${scLabel(v.score)}</span></td></tr>`).join('')+'</tbody></table>'}
function demo(){dbName=$('reportName').value||'Rotagyn';vehicles=[['UDV2F12','UDV2F12 | CITROEN BASALT',25,0,0,0,0,0,0,1,'15/06/2026 08:31'],['SRG8B64','BYD SEAL | SRG8B64 | TESTE GO9 4G',25,0,0,0,0,0,0,1,'14/06/2026 17:12'],['SDJ0J48','SDJ0J48 | Fiat Cronos',25,11,0,0,0,0,0,1,'12/06/2026 09:02'],['Teste GO Focus','Teste GO Focus',45,11,0,0,0,0,0,0,'-'],['FOM4A84','FOM4A84 | Jeep Commander',75,0,0,0,1,0,0,0,'-']].map((r,i)=>({id:'d'+i,placa:r[0],nome:r[1],score:r[2],dias:r[3],reboots:r[4],gps:r[5],vlow:r[6],vhigh:r[7],faults:r[8],unplugged:r[9],removalDatesText:r[10],lastRemovalDate:r[10]}));filtered=[...vehicles];status('Demo');alertMsg('Dados simulados carregados com datas de possível remoção.','ok');render()}
function exportCSV(){if(!filtered.length)return;const rows=[['nome','placa','score','status','problema_principal','dias_sem_dados','datas_possivel_remocao','reboots','falhas_gps','tensao_fora']].concat(filtered.map(v=>[v.nome,v.placa,v.score,scLabel(v.score),problem(v),v.dias,v.removalDatesText||'-',v.reboots,v.gps,v.vlow+v.vhigh]));const csv=rows.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fleet-health-report-'+clean(dbName)+'.csv';a.click();URL.revokeObjectURL(a.href)}
function init(api,state){apiRef=api;stateRef=state||{};dbName=getDb(api,stateRef);shell();if(api)load(api);else demo()}
if(!window.geotab)window.geotab={addin:{}};if(!window.geotab.addin)window.geotab.addin={};window.geotab.addin.fleetHealthScore=function(){return{initialize:function(api,state,cb){try{init(api,state)}catch(e){console.error(e)}if(cb)cb()},focus:function(){},blur:function(){}}};if(!window.location.href.includes('my.geotab'))setTimeout(()=>init(null,{}),50);
})();
